apiVersion: v1
kind: Service
metadata:
  name: {{ include "ravendb.name" . }}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    app.kubernetes.io/name: {{ include "ravendb.name" . }}
    helm.sh/chart: {{ include "ravendb.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    metallb.universe.tf/allow-shared-ip: ravendb
spec:
  type: {{ .Values.service.type }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 443
      protocol: TCP
      name: https
    - port: 38888
      targetPort: 38888
      protocol: TCP
      name: tcp
  selector:
    app: {{ include "ravendb.name" . }}
